INSERT INTO strings (stringname, string) VALUES
('game_menu', 'Game'),
('editor_menu', 'Editor'),
('place_menu', 'Place'),
('thing_menu', 'Thing'),
('new_map', 'New world'),
('open_map', 'Open world...'),
('save_map', 'Save'),
('quit_maped', 'Quit'),
('ed_select', 'Select...'),
('ed_copy', 'Copy'),
('ed_paste', 'Paste'),
('ed_delete', 'Delete...'),
('custplace', 'New place...'),
('workplace', 'New workplace...'),
('commonplace', 'New commons...'),
('lairplace', 'New lair...'),
('custthing', 'New thing...'),
('decorthing', 'New decoration...'),
('clothing', 'New clothing...'),
('toolthing', 'New tool...');
