-- This file is part of LiSE, a framework for life simulation games.
-- Copyright (c) 2013 Zachary Spector,  zacharyspector@gmail.com
INSERT INTO strings (stringname, string) VALUES
('game_menu', 'Game'),
('editor_menu', 'Editor'),
('place_menu', 'Place'),
('thing_menu', 'Thing'),
('portal_menu', 'Portal'),
('new_map', 'New world'),
('open_map', 'Open world...'),
('save_map', 'Save'),
('quit_maped', 'Quit'),
('ed_select', 'Select...'),
('ed_copy', 'Copy'),
('ed_paste', 'Paste'),
('ed_delete', 'Delete...'),
('custplace', 'New place...'),
('workplace', 'New workplace...'),
('commonplace', 'New commons...'),
('lairplace', 'New lair...'),
('custthing', 'New thing...'),
('decorthing', 'New decoration...'),
('clothing', 'New clothing...'),
('toolthing', 'New tool...'),
('branch', 'Branch'),
('tick', 'Tick'),
('putthing', 'Drag this thing to where you want it.'),
('putplace', 'Drag this place where you want it.'),
('play', '▶'),
('reverse', ''),
('forward', ''),
('switch', '⇆'),
('pause', '‖'),
('end', '⏭'),
('beginning', '⏮'),
('stepforward', '↳'),
('stepbackward', '↰'),
('speedup', '⏩'),
('slowdown', '⏪'),
('next_branch', '➦'),
('prev_branch', ''),
('database', '📸'),
('calendar', '📅'),
('feed', ''),
('edit', '✎'),
('tools', '⚒'),
('cog', '⚙'),
('map', ''),
('save', '💾'),
('locked', '🔒'),
('unlocked', '🔓'),
('launch', '🚀'),
('split', '🕪'),
('bookmark', '🔖'),
('bookmarks', '📑'),
('character', '👤'),
('characters', '👥'),
('newchar', ''),
('charsheet', ''),
('delete', ''),
('db', '📸'),
('network', ''),
('night', '☽'),
('day', '🔆');
