import networkx as nx
import pytest


def test_btt(handle_initialized):
	assert handle_initialized.get_btt() == ("trunk", 0, 156)


def test_language(handle_initialized):
	assert handle_initialized.get_language() == "eng"
	handle_initialized.set_string("foo", "bar")
	assert handle_initialized.get_string_lang_items("eng") == [("foo", "bar")]
	handle_initialized.set_language("esp")
	assert handle_initialized.get_language() == "esp"
	assert handle_initialized.get_string_lang_items("esp") == []
	assert handle_initialized.get_string_lang_items() == []
	handle_initialized.set_language("eng")
	assert handle_initialized.get_string_lang_items() == [("foo", "bar")]
	assert handle_initialized.strings_copy() == {"foo": "bar"}
	handle_initialized.del_string("foo")
	handle_initialized.set_language("esp")
	assert handle_initialized.strings_copy("eng") == {}


def test_eternal(handle_initialized):
	unpack = handle_initialized.unpack
	assert unpack(handle_initialized.get_eternal("_lise_schema_version")) == 0
	assert unpack(handle_initialized.get_eternal("main_branch")) == "trunk"
	assert unpack(handle_initialized.get_eternal("language")) == "eng"
	handle_initialized.set_eternal("haha", "lol")
	assert unpack(handle_initialized.get_eternal("haha")) == "lol"
	handle_initialized.del_eternal("branch")
	with pytest.raises(KeyError):
		handle_initialized.get_eternal("branch")
	assert handle_initialized.eternal_copy() == {
		b"\xb4_lise_schema_version": b"\x00",
		b"\xabmain_branch": b"\xa5trunk",
		b"\xa4turn": b"\x00",
		b"\xa4tick": b"\x00",
		b"\xa8language": b"\xa3eng",
		b"\xa4haha": b"\xa3lol",
	}


def test_universal(handle_initialized):
	handle_initialized.set_universal("foo", "bar")
	handle_initialized.set_universal("spam", "tasty")
	univ = handle_initialized.snap_keyframe()["universal"]
	assert univ["foo"] == "bar"
	assert univ["spam"] == "tasty"
	handle_initialized.del_universal("foo")
	univ = handle_initialized.snap_keyframe()["universal"]
	assert "foo" not in univ
	assert univ["spam"] == "tasty"


def test_character(handle_initialized):
	origtime = handle_initialized.get_btt()
	handle_initialized.add_character(
		"hello",
		{
			"node": {
				"hi": {"yes": "very yes"},
				"hello": {"you": "smart"},
				"morning": {"good": 100},
				"salutations": {},
			},
			"thing": {"me": {"location": "hi"}},
			"edge": {"hi": {"hello": {"good": "morning"}}},
		},
		{"stat": "also"},
	)
	assert handle_initialized.node_exists("hello", "hi")
	handle_initialized.set_character_stat("hello", "stoat", "bitter")
	handle_initialized.del_character_stat("hello", "stat")
	handle_initialized.set_node_stat("hello", "hi", "no", "very no")
	handle_initialized.del_node_stat("hello", "hi", "yes")
	handle_initialized.del_character("physical")
	handle_initialized.del_node("hello", "salutations")
	handle_initialized.update_nodes(
		"hello",
		{"hi": {"tainted": True}, "bye": {"toodles": False}, "morning": None},
	)
	handle_initialized.set_thing(
		"hello", "evening", {"location": "bye", "moon": 1.0}
	)
	handle_initialized.add_thing(
		"hello", "moon", "evening", {"phase": "waxing gibbous"}
	)
	handle_initialized.character_set_node_predecessors(
		"hello", "bye", {"hi": {"is-an-edge": True}}
	)
	handle_initialized.add_thing("hello", "neal", "hi", {})
	handle_initialized.set_thing_location("hello", "neal", "moon")
	handle_initialized.set_place("hello", "earth", {})
	handle_initialized.add_portal("hello", "moon", "earth", {})
	assert handle_initialized.thing_travel_to("hello", "neal", "earth") == 1
	kf = handle_initialized.snap_keyframe()
	del kf["universal"]
	assert kf == {
		"graph_val": {("hello",): {"stat": None, "stoat": "bitter"}},
		"nodes": {
			("hello",): {
				"hi": True,
				"hello": True,
				"me": True,
				"bye": True,
				"evening": True,
				"moon": True,
				"neal": True,
				"earth": True,
			}
		},
		"node_val": {
			("hello", "hi"): {"name": "hi", "no": "very no", "tainted": True},
			("hello", "hello"): {"name": "hello", "you": "smart"},
			("hello", "me"): {"name": "me", "location": "hi"},
			("hello", "bye"): {"name": "bye", "toodles": False},
			("hello", "evening"): {
				"name": "evening",
				"moon": 1.0,
				"location": "bye",
			},
			("hello", "moon"): {
				"name": "moon",
				"phase": "waxing gibbous",
				"location": "evening",
			},
			("hello", "neal"): {"name": "neal", "location": "moon"},
			("hello", "earth"): {"name": "earth"},
		},
		"edges": {
			("hello", "hi", "hello"): {0: True},
			("hello", "bye", "hi"): {0: True},
			("hello", "moon", "earth"): {0: True},
		},
		"edge_val": {
			("hello", "hi", "hello", 0): {"good": "morning"},
			("hello", "bye", "hi", 0): {},
			("hello", "moon", "earth", 0): {},
		},
		"triggers": {
			"shrubsprint": ("uncovered", "breakcover"),
			"fight": ("sametile",),
			"kill_kobold": ("kobold_alive",),
			"go2kobold": ("aware",),
			"wander": ("standing_still",),
		},
		"prereqs": {
			"shrubsprint": ("not_traveling",),
			"fight": ("kobold_alive", "aware"),
			"kill_kobold": ("unmerciful",),
			"go2kobold": ("kobold_alive", "kobold_not_here"),
			"wander": (),
		},
		"actions": {
			"shrubsprint": ("shrubsprint",),
			"fight": ("fight",),
			"kill_kobold": ("kill_kobold",),
			"go2kobold": ("go2kobold",),
			"wander": ("wander",),
		},
		"rulebook": {
			("physical", "kobold"): (["shrubsprint"], 0.0),
			("physical", "dwarf"): (
				["fight", "kill_kobold", "go2kobold", "wander"],
				0.0,
			),
		},
	}
	handle_initialized.time_travel(*origtime)
	kf = handle_initialized.snap_keyframe()
	del kf["universal"]
	assert kf == {
		"graph_val": {("hello",): {"stat": "also"}, ("physical",): {}},
		"nodes": {
			("physical",): {
				(0, 0): True,
				(0, 1): True,
				(0, 2): True,
				(0, 3): True,
				(0, 4): True,
				(0, 5): True,
				(0, 6): True,
				(0, 7): True,
				(0, 8): True,
				(0, 9): True,
				(1, 0): True,
				(1, 1): True,
				(1, 2): True,
				(1, 3): True,
				(1, 4): True,
				(1, 5): True,
				(1, 6): True,
				(1, 7): True,
				(1, 8): True,
				(1, 9): True,
				(2, 0): True,
				(2, 1): True,
				(2, 2): True,
				(2, 3): True,
				(2, 4): True,
				(2, 5): True,
				(2, 6): True,
				(2, 7): True,
				(2, 8): True,
				(2, 9): True,
				(3, 0): True,
				(3, 1): True,
				(3, 2): True,
				(3, 3): True,
				(3, 4): True,
				(3, 5): True,
				(3, 6): True,
				(3, 7): True,
				(3, 8): True,
				(3, 9): True,
				(4, 0): True,
				(4, 1): True,
				(4, 2): True,
				(4, 3): True,
				(4, 4): True,
				(4, 5): True,
				(4, 6): True,
				(4, 7): True,
				(4, 8): True,
				(4, 9): True,
				(5, 0): True,
				(5, 1): True,
				(5, 2): True,
				(5, 3): True,
				(5, 4): True,
				(5, 5): True,
				(5, 6): True,
				(5, 7): True,
				(5, 8): True,
				(5, 9): True,
				(6, 0): True,
				(6, 1): True,
				(6, 2): True,
				(6, 3): True,
				(6, 4): True,
				(6, 5): True,
				(6, 6): True,
				(6, 7): True,
				(6, 8): True,
				(6, 9): True,
				(7, 0): True,
				(7, 1): True,
				(7, 2): True,
				(7, 3): True,
				(7, 4): True,
				(7, 5): True,
				(7, 6): True,
				(7, 7): True,
				(7, 8): True,
				(7, 9): True,
				(8, 0): True,
				(8, 1): True,
				(8, 2): True,
				(8, 3): True,
				(8, 4): True,
				(8, 5): True,
				(8, 6): True,
				(8, 7): True,
				(8, 8): True,
				(8, 9): True,
				(9, 0): True,
				(9, 1): True,
				(9, 2): True,
				(9, 3): True,
				(9, 4): True,
				(9, 5): True,
				(9, 6): True,
				(9, 7): True,
				(9, 8): True,
				(9, 9): True,
				"kobold": True,
				"dwarf": True,
				"shrub0": True,
				"shrub1": True,
				"shrub2": True,
				"shrub3": True,
				"shrub4": True,
				"shrub5": True,
				"shrub6": True,
				"shrub7": True,
				"shrub8": True,
				"shrub9": True,
				"shrub10": True,
				"shrub11": True,
				"shrub12": True,
				"shrub13": True,
				"shrub14": True,
				"shrub15": True,
				"shrub16": True,
				"shrub17": True,
				"shrub18": True,
				"shrub19": True,
			},
			("hello",): {},
		},
		"node_val": {
			("physical", (0, 0)): {},
			("physical", (0, 1)): {},
			("physical", (0, 2)): {},
			("physical", (0, 3)): {},
			("physical", (0, 4)): {},
			("physical", (0, 5)): {},
			("physical", (0, 6)): {},
			("physical", (0, 7)): {},
			("physical", (0, 8)): {},
			("physical", (0, 9)): {},
			("physical", (1, 0)): {},
			("physical", (1, 1)): {},
			("physical", (1, 2)): {},
			("physical", (1, 3)): {},
			("physical", (1, 4)): {},
			("physical", (1, 5)): {},
			("physical", (1, 6)): {},
			("physical", (1, 7)): {},
			("physical", (1, 8)): {},
			("physical", (1, 9)): {},
			("physical", (2, 0)): {},
			("physical", (2, 1)): {},
			("physical", (2, 2)): {},
			("physical", (2, 3)): {},
			("physical", (2, 4)): {},
			("physical", (2, 5)): {},
			("physical", (2, 6)): {},
			("physical", (2, 7)): {},
			("physical", (2, 8)): {},
			("physical", (2, 9)): {},
			("physical", (3, 0)): {},
			("physical", (3, 1)): {},
			("physical", (3, 2)): {},
			("physical", (3, 3)): {},
			("physical", (3, 4)): {},
			("physical", (3, 5)): {},
			("physical", (3, 6)): {},
			("physical", (3, 7)): {},
			("physical", (3, 8)): {},
			("physical", (3, 9)): {},
			("physical", (4, 0)): {},
			("physical", (4, 1)): {},
			("physical", (4, 2)): {},
			("physical", (4, 3)): {},
			("physical", (4, 4)): {},
			("physical", (4, 5)): {},
			("physical", (4, 6)): {},
			("physical", (4, 7)): {},
			("physical", (4, 8)): {},
			("physical", (4, 9)): {},
			("physical", (5, 0)): {},
			("physical", (5, 1)): {},
			("physical", (5, 2)): {},
			("physical", (5, 3)): {},
			("physical", (5, 4)): {},
			("physical", (5, 5)): {},
			("physical", (5, 6)): {},
			("physical", (5, 7)): {},
			("physical", (5, 8)): {},
			("physical", (5, 9)): {},
			("physical", (6, 0)): {},
			("physical", (6, 1)): {},
			("physical", (6, 2)): {},
			("physical", (6, 3)): {},
			("physical", (6, 4)): {},
			("physical", (6, 5)): {},
			("physical", (6, 6)): {},
			("physical", (6, 7)): {},
			("physical", (6, 8)): {},
			("physical", (6, 9)): {},
			("physical", (7, 0)): {},
			("physical", (7, 1)): {},
			("physical", (7, 2)): {},
			("physical", (7, 3)): {},
			("physical", (7, 4)): {},
			("physical", (7, 5)): {},
			("physical", (7, 6)): {},
			("physical", (7, 7)): {},
			("physical", (7, 8)): {},
			("physical", (7, 9)): {},
			("physical", (8, 0)): {},
			("physical", (8, 1)): {},
			("physical", (8, 2)): {},
			("physical", (8, 3)): {},
			("physical", (8, 4)): {},
			("physical", (8, 5)): {},
			("physical", (8, 6)): {},
			("physical", (8, 7)): {},
			("physical", (8, 8)): {},
			("physical", (8, 9)): {},
			("physical", (9, 0)): {},
			("physical", (9, 1)): {},
			("physical", (9, 2)): {},
			("physical", (9, 3)): {},
			("physical", (9, 4)): {},
			("physical", (9, 5)): {},
			("physical", (9, 6)): {},
			("physical", (9, 7)): {},
			("physical", (9, 8)): {},
			("physical", (9, 9)): {},
			("physical", "kobold"): {
				"name": "kobold",
				"sprint_chance": 0.9,
				"_image_paths": ["atlas://rltiles/base.atlas/kobold_m"],
				"shrub_places": [
					(1, 9),
					(2, 2),
					(6, 0),
					(7, 4),
					(5, 0),
					(6, 5),
					(9, 9),
					(8, 5),
					(2, 3),
					(5, 7),
					(9, 0),
					(1, 6),
					(7, 3),
					(1, 8),
					(3, 9),
					(2, 9),
					(4, 5),
					(4, 2),
					(3, 8),
					(0, 1),
				],
				"location": (9, 9),
			},
			("physical", "dwarf"): {
				"name": "dwarf",
				"sight_radius": 2,
				"seen_kobold": False,
				"_image_paths": ["atlas://rltiles/base.atlas/dwarf_m"],
				"location": (0, 0),
			},
			("physical", "shrub0"): {
				"name": "shrub0",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (1, 9),
			},
			("physical", "shrub1"): {
				"name": "shrub1",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (2, 2),
			},
			("physical", "shrub2"): {
				"name": "shrub2",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (6, 0),
			},
			("physical", "shrub3"): {
				"name": "shrub3",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (7, 4),
			},
			("physical", "shrub4"): {
				"name": "shrub4",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (5, 0),
			},
			("physical", "shrub5"): {
				"name": "shrub5",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (6, 5),
			},
			("physical", "shrub6"): {
				"name": "shrub6",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (9, 9),
			},
			("physical", "shrub7"): {
				"name": "shrub7",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (8, 5),
			},
			("physical", "shrub8"): {
				"name": "shrub8",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (2, 3),
			},
			("physical", "shrub9"): {
				"name": "shrub9",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (5, 7),
			},
			("physical", "shrub10"): {
				"name": "shrub10",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (9, 0),
			},
			("physical", "shrub11"): {
				"name": "shrub11",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (1, 6),
			},
			("physical", "shrub12"): {
				"name": "shrub12",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (7, 3),
			},
			("physical", "shrub13"): {
				"name": "shrub13",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (1, 8),
			},
			("physical", "shrub14"): {
				"name": "shrub14",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (3, 9),
			},
			("physical", "shrub15"): {
				"name": "shrub15",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (2, 9),
			},
			("physical", "shrub16"): {
				"name": "shrub16",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (4, 5),
			},
			("physical", "shrub17"): {
				"name": "shrub17",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (4, 2),
			},
			("physical", "shrub18"): {
				"name": "shrub18",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (3, 8),
			},
			("physical", "shrub19"): {
				"name": "shrub19",
				"cover": 1,
				"_image_paths": ["atlas://rltiles/dc-mon.atlas/fungus"],
				"_group": "shrub",
				"location": (0, 1),
			},
		},
		"edges": {
			("physical", (0, 0), (1, 0)): {0: True},
			("physical", (0, 0), (0, 1)): {0: True},
			("physical", (0, 1), (1, 1)): {0: True},
			("physical", (0, 1), (0, 0)): {0: True},
			("physical", (0, 1), (0, 2)): {0: True},
			("physical", (0, 2), (1, 2)): {0: True},
			("physical", (0, 2), (0, 1)): {0: True},
			("physical", (0, 2), (0, 3)): {0: True},
			("physical", (0, 3), (1, 3)): {0: True},
			("physical", (0, 3), (0, 2)): {0: True},
			("physical", (0, 3), (0, 4)): {0: True},
			("physical", (0, 4), (1, 4)): {0: True},
			("physical", (0, 4), (0, 3)): {0: True},
			("physical", (0, 4), (0, 5)): {0: True},
			("physical", (0, 5), (1, 5)): {0: True},
			("physical", (0, 5), (0, 4)): {0: True},
			("physical", (0, 5), (0, 6)): {0: True},
			("physical", (0, 6), (1, 6)): {0: True},
			("physical", (0, 6), (0, 5)): {0: True},
			("physical", (0, 6), (0, 7)): {0: True},
			("physical", (0, 7), (1, 7)): {0: True},
			("physical", (0, 7), (0, 6)): {0: True},
			("physical", (0, 7), (0, 8)): {0: True},
			("physical", (0, 8), (1, 8)): {0: True},
			("physical", (0, 8), (0, 7)): {0: True},
			("physical", (0, 8), (0, 9)): {0: True},
			("physical", (0, 9), (1, 9)): {0: True},
			("physical", (0, 9), (0, 8)): {0: True},
			("physical", (1, 0), (0, 0)): {0: True},
			("physical", (1, 0), (2, 0)): {0: True},
			("physical", (1, 0), (1, 1)): {0: True},
			("physical", (1, 1), (0, 1)): {0: True},
			("physical", (1, 1), (2, 1)): {0: True},
			("physical", (1, 1), (1, 0)): {0: True},
			("physical", (1, 1), (1, 2)): {0: True},
			("physical", (1, 2), (0, 2)): {0: True},
			("physical", (1, 2), (2, 2)): {0: True},
			("physical", (1, 2), (1, 1)): {0: True},
			("physical", (1, 2), (1, 3)): {0: True},
			("physical", (1, 3), (0, 3)): {0: True},
			("physical", (1, 3), (2, 3)): {0: True},
			("physical", (1, 3), (1, 2)): {0: True},
			("physical", (1, 3), (1, 4)): {0: True},
			("physical", (1, 4), (0, 4)): {0: True},
			("physical", (1, 4), (2, 4)): {0: True},
			("physical", (1, 4), (1, 3)): {0: True},
			("physical", (1, 4), (1, 5)): {0: True},
			("physical", (1, 5), (0, 5)): {0: True},
			("physical", (1, 5), (2, 5)): {0: True},
			("physical", (1, 5), (1, 4)): {0: True},
			("physical", (1, 5), (1, 6)): {0: True},
			("physical", (1, 6), (0, 6)): {0: True},
			("physical", (1, 6), (2, 6)): {0: True},
			("physical", (1, 6), (1, 5)): {0: True},
			("physical", (1, 6), (1, 7)): {0: True},
			("physical", (1, 7), (0, 7)): {0: True},
			("physical", (1, 7), (2, 7)): {0: True},
			("physical", (1, 7), (1, 6)): {0: True},
			("physical", (1, 7), (1, 8)): {0: True},
			("physical", (1, 8), (0, 8)): {0: True},
			("physical", (1, 8), (2, 8)): {0: True},
			("physical", (1, 8), (1, 7)): {0: True},
			("physical", (1, 8), (1, 9)): {0: True},
			("physical", (1, 9), (0, 9)): {0: True},
			("physical", (1, 9), (2, 9)): {0: True},
			("physical", (1, 9), (1, 8)): {0: True},
			("physical", (2, 0), (1, 0)): {0: True},
			("physical", (2, 0), (3, 0)): {0: True},
			("physical", (2, 0), (2, 1)): {0: True},
			("physical", (2, 1), (1, 1)): {0: True},
			("physical", (2, 1), (3, 1)): {0: True},
			("physical", (2, 1), (2, 0)): {0: True},
			("physical", (2, 1), (2, 2)): {0: True},
			("physical", (2, 2), (1, 2)): {0: True},
			("physical", (2, 2), (3, 2)): {0: True},
			("physical", (2, 2), (2, 1)): {0: True},
			("physical", (2, 2), (2, 3)): {0: True},
			("physical", (2, 3), (1, 3)): {0: True},
			("physical", (2, 3), (3, 3)): {0: True},
			("physical", (2, 3), (2, 2)): {0: True},
			("physical", (2, 3), (2, 4)): {0: True},
			("physical", (2, 4), (1, 4)): {0: True},
			("physical", (2, 4), (3, 4)): {0: True},
			("physical", (2, 4), (2, 3)): {0: True},
			("physical", (2, 4), (2, 5)): {0: True},
			("physical", (2, 5), (1, 5)): {0: True},
			("physical", (2, 5), (3, 5)): {0: True},
			("physical", (2, 5), (2, 4)): {0: True},
			("physical", (2, 5), (2, 6)): {0: True},
			("physical", (2, 6), (1, 6)): {0: True},
			("physical", (2, 6), (3, 6)): {0: True},
			("physical", (2, 6), (2, 5)): {0: True},
			("physical", (2, 6), (2, 7)): {0: True},
			("physical", (2, 7), (1, 7)): {0: True},
			("physical", (2, 7), (3, 7)): {0: True},
			("physical", (2, 7), (2, 6)): {0: True},
			("physical", (2, 7), (2, 8)): {0: True},
			("physical", (2, 8), (1, 8)): {0: True},
			("physical", (2, 8), (3, 8)): {0: True},
			("physical", (2, 8), (2, 7)): {0: True},
			("physical", (2, 8), (2, 9)): {0: True},
			("physical", (2, 9), (1, 9)): {0: True},
			("physical", (2, 9), (3, 9)): {0: True},
			("physical", (2, 9), (2, 8)): {0: True},
			("physical", (3, 0), (2, 0)): {0: True},
			("physical", (3, 0), (4, 0)): {0: True},
			("physical", (3, 0), (3, 1)): {0: True},
			("physical", (3, 1), (2, 1)): {0: True},
			("physical", (3, 1), (4, 1)): {0: True},
			("physical", (3, 1), (3, 0)): {0: True},
			("physical", (3, 1), (3, 2)): {0: True},
			("physical", (3, 2), (2, 2)): {0: True},
			("physical", (3, 2), (4, 2)): {0: True},
			("physical", (3, 2), (3, 1)): {0: True},
			("physical", (3, 2), (3, 3)): {0: True},
			("physical", (3, 3), (2, 3)): {0: True},
			("physical", (3, 3), (4, 3)): {0: True},
			("physical", (3, 3), (3, 2)): {0: True},
			("physical", (3, 3), (3, 4)): {0: True},
			("physical", (3, 4), (2, 4)): {0: True},
			("physical", (3, 4), (4, 4)): {0: True},
			("physical", (3, 4), (3, 3)): {0: True},
			("physical", (3, 4), (3, 5)): {0: True},
			("physical", (3, 5), (2, 5)): {0: True},
			("physical", (3, 5), (4, 5)): {0: True},
			("physical", (3, 5), (3, 4)): {0: True},
			("physical", (3, 5), (3, 6)): {0: True},
			("physical", (3, 6), (2, 6)): {0: True},
			("physical", (3, 6), (4, 6)): {0: True},
			("physical", (3, 6), (3, 5)): {0: True},
			("physical", (3, 6), (3, 7)): {0: True},
			("physical", (3, 7), (2, 7)): {0: True},
			("physical", (3, 7), (4, 7)): {0: True},
			("physical", (3, 7), (3, 6)): {0: True},
			("physical", (3, 7), (3, 8)): {0: True},
			("physical", (3, 8), (2, 8)): {0: True},
			("physical", (3, 8), (4, 8)): {0: True},
			("physical", (3, 8), (3, 7)): {0: True},
			("physical", (3, 8), (3, 9)): {0: True},
			("physical", (3, 9), (2, 9)): {0: True},
			("physical", (3, 9), (4, 9)): {0: True},
			("physical", (3, 9), (3, 8)): {0: True},
			("physical", (4, 0), (3, 0)): {0: True},
			("physical", (4, 0), (5, 0)): {0: True},
			("physical", (4, 0), (4, 1)): {0: True},
			("physical", (4, 1), (3, 1)): {0: True},
			("physical", (4, 1), (5, 1)): {0: True},
			("physical", (4, 1), (4, 0)): {0: True},
			("physical", (4, 1), (4, 2)): {0: True},
			("physical", (4, 2), (3, 2)): {0: True},
			("physical", (4, 2), (5, 2)): {0: True},
			("physical", (4, 2), (4, 1)): {0: True},
			("physical", (4, 2), (4, 3)): {0: True},
			("physical", (4, 3), (3, 3)): {0: True},
			("physical", (4, 3), (5, 3)): {0: True},
			("physical", (4, 3), (4, 2)): {0: True},
			("physical", (4, 3), (4, 4)): {0: True},
			("physical", (4, 4), (3, 4)): {0: True},
			("physical", (4, 4), (5, 4)): {0: True},
			("physical", (4, 4), (4, 3)): {0: True},
			("physical", (4, 4), (4, 5)): {0: True},
			("physical", (4, 5), (3, 5)): {0: True},
			("physical", (4, 5), (5, 5)): {0: True},
			("physical", (4, 5), (4, 4)): {0: True},
			("physical", (4, 5), (4, 6)): {0: True},
			("physical", (4, 6), (3, 6)): {0: True},
			("physical", (4, 6), (5, 6)): {0: True},
			("physical", (4, 6), (4, 5)): {0: True},
			("physical", (4, 6), (4, 7)): {0: True},
			("physical", (4, 7), (3, 7)): {0: True},
			("physical", (4, 7), (5, 7)): {0: True},
			("physical", (4, 7), (4, 6)): {0: True},
			("physical", (4, 7), (4, 8)): {0: True},
			("physical", (4, 8), (3, 8)): {0: True},
			("physical", (4, 8), (5, 8)): {0: True},
			("physical", (4, 8), (4, 7)): {0: True},
			("physical", (4, 8), (4, 9)): {0: True},
			("physical", (4, 9), (3, 9)): {0: True},
			("physical", (4, 9), (5, 9)): {0: True},
			("physical", (4, 9), (4, 8)): {0: True},
			("physical", (5, 0), (4, 0)): {0: True},
			("physical", (5, 0), (6, 0)): {0: True},
			("physical", (5, 0), (5, 1)): {0: True},
			("physical", (5, 1), (4, 1)): {0: True},
			("physical", (5, 1), (6, 1)): {0: True},
			("physical", (5, 1), (5, 0)): {0: True},
			("physical", (5, 1), (5, 2)): {0: True},
			("physical", (5, 2), (4, 2)): {0: True},
			("physical", (5, 2), (6, 2)): {0: True},
			("physical", (5, 2), (5, 1)): {0: True},
			("physical", (5, 2), (5, 3)): {0: True},
			("physical", (5, 3), (4, 3)): {0: True},
			("physical", (5, 3), (6, 3)): {0: True},
			("physical", (5, 3), (5, 2)): {0: True},
			("physical", (5, 3), (5, 4)): {0: True},
			("physical", (5, 4), (4, 4)): {0: True},
			("physical", (5, 4), (6, 4)): {0: True},
			("physical", (5, 4), (5, 3)): {0: True},
			("physical", (5, 4), (5, 5)): {0: True},
			("physical", (5, 5), (4, 5)): {0: True},
			("physical", (5, 5), (6, 5)): {0: True},
			("physical", (5, 5), (5, 4)): {0: True},
			("physical", (5, 5), (5, 6)): {0: True},
			("physical", (5, 6), (4, 6)): {0: True},
			("physical", (5, 6), (6, 6)): {0: True},
			("physical", (5, 6), (5, 5)): {0: True},
			("physical", (5, 6), (5, 7)): {0: True},
			("physical", (5, 7), (4, 7)): {0: True},
			("physical", (5, 7), (6, 7)): {0: True},
			("physical", (5, 7), (5, 6)): {0: True},
			("physical", (5, 7), (5, 8)): {0: True},
			("physical", (5, 8), (4, 8)): {0: True},
			("physical", (5, 8), (6, 8)): {0: True},
			("physical", (5, 8), (5, 7)): {0: True},
			("physical", (5, 8), (5, 9)): {0: True},
			("physical", (5, 9), (4, 9)): {0: True},
			("physical", (5, 9), (6, 9)): {0: True},
			("physical", (5, 9), (5, 8)): {0: True},
			("physical", (6, 0), (5, 0)): {0: True},
			("physical", (6, 0), (7, 0)): {0: True},
			("physical", (6, 0), (6, 1)): {0: True},
			("physical", (6, 1), (5, 1)): {0: True},
			("physical", (6, 1), (7, 1)): {0: True},
			("physical", (6, 1), (6, 0)): {0: True},
			("physical", (6, 1), (6, 2)): {0: True},
			("physical", (6, 2), (5, 2)): {0: True},
			("physical", (6, 2), (7, 2)): {0: True},
			("physical", (6, 2), (6, 1)): {0: True},
			("physical", (6, 2), (6, 3)): {0: True},
			("physical", (6, 3), (5, 3)): {0: True},
			("physical", (6, 3), (7, 3)): {0: True},
			("physical", (6, 3), (6, 2)): {0: True},
			("physical", (6, 3), (6, 4)): {0: True},
			("physical", (6, 4), (5, 4)): {0: True},
			("physical", (6, 4), (7, 4)): {0: True},
			("physical", (6, 4), (6, 3)): {0: True},
			("physical", (6, 4), (6, 5)): {0: True},
			("physical", (6, 5), (5, 5)): {0: True},
			("physical", (6, 5), (7, 5)): {0: True},
			("physical", (6, 5), (6, 4)): {0: True},
			("physical", (6, 5), (6, 6)): {0: True},
			("physical", (6, 6), (5, 6)): {0: True},
			("physical", (6, 6), (7, 6)): {0: True},
			("physical", (6, 6), (6, 5)): {0: True},
			("physical", (6, 6), (6, 7)): {0: True},
			("physical", (6, 7), (5, 7)): {0: True},
			("physical", (6, 7), (7, 7)): {0: True},
			("physical", (6, 7), (6, 6)): {0: True},
			("physical", (6, 7), (6, 8)): {0: True},
			("physical", (6, 8), (5, 8)): {0: True},
			("physical", (6, 8), (7, 8)): {0: True},
			("physical", (6, 8), (6, 7)): {0: True},
			("physical", (6, 8), (6, 9)): {0: True},
			("physical", (6, 9), (5, 9)): {0: True},
			("physical", (6, 9), (7, 9)): {0: True},
			("physical", (6, 9), (6, 8)): {0: True},
			("physical", (7, 0), (6, 0)): {0: True},
			("physical", (7, 0), (8, 0)): {0: True},
			("physical", (7, 0), (7, 1)): {0: True},
			("physical", (7, 1), (6, 1)): {0: True},
			("physical", (7, 1), (8, 1)): {0: True},
			("physical", (7, 1), (7, 0)): {0: True},
			("physical", (7, 1), (7, 2)): {0: True},
			("physical", (7, 2), (6, 2)): {0: True},
			("physical", (7, 2), (8, 2)): {0: True},
			("physical", (7, 2), (7, 1)): {0: True},
			("physical", (7, 2), (7, 3)): {0: True},
			("physical", (7, 3), (6, 3)): {0: True},
			("physical", (7, 3), (8, 3)): {0: True},
			("physical", (7, 3), (7, 2)): {0: True},
			("physical", (7, 3), (7, 4)): {0: True},
			("physical", (7, 4), (6, 4)): {0: True},
			("physical", (7, 4), (8, 4)): {0: True},
			("physical", (7, 4), (7, 3)): {0: True},
			("physical", (7, 4), (7, 5)): {0: True},
			("physical", (7, 5), (6, 5)): {0: True},
			("physical", (7, 5), (8, 5)): {0: True},
			("physical", (7, 5), (7, 4)): {0: True},
			("physical", (7, 5), (7, 6)): {0: True},
			("physical", (7, 6), (6, 6)): {0: True},
			("physical", (7, 6), (8, 6)): {0: True},
			("physical", (7, 6), (7, 5)): {0: True},
			("physical", (7, 6), (7, 7)): {0: True},
			("physical", (7, 7), (6, 7)): {0: True},
			("physical", (7, 7), (8, 7)): {0: True},
			("physical", (7, 7), (7, 6)): {0: True},
			("physical", (7, 7), (7, 8)): {0: True},
			("physical", (7, 8), (6, 8)): {0: True},
			("physical", (7, 8), (8, 8)): {0: True},
			("physical", (7, 8), (7, 7)): {0: True},
			("physical", (7, 8), (7, 9)): {0: True},
			("physical", (7, 9), (6, 9)): {0: True},
			("physical", (7, 9), (8, 9)): {0: True},
			("physical", (7, 9), (7, 8)): {0: True},
			("physical", (8, 0), (7, 0)): {0: True},
			("physical", (8, 0), (9, 0)): {0: True},
			("physical", (8, 0), (8, 1)): {0: True},
			("physical", (8, 1), (7, 1)): {0: True},
			("physical", (8, 1), (9, 1)): {0: True},
			("physical", (8, 1), (8, 0)): {0: True},
			("physical", (8, 1), (8, 2)): {0: True},
			("physical", (8, 2), (7, 2)): {0: True},
			("physical", (8, 2), (9, 2)): {0: True},
			("physical", (8, 2), (8, 1)): {0: True},
			("physical", (8, 2), (8, 3)): {0: True},
			("physical", (8, 3), (7, 3)): {0: True},
			("physical", (8, 3), (9, 3)): {0: True},
			("physical", (8, 3), (8, 2)): {0: True},
			("physical", (8, 3), (8, 4)): {0: True},
			("physical", (8, 4), (7, 4)): {0: True},
			("physical", (8, 4), (9, 4)): {0: True},
			("physical", (8, 4), (8, 3)): {0: True},
			("physical", (8, 4), (8, 5)): {0: True},
			("physical", (8, 5), (7, 5)): {0: True},
			("physical", (8, 5), (9, 5)): {0: True},
			("physical", (8, 5), (8, 4)): {0: True},
			("physical", (8, 5), (8, 6)): {0: True},
			("physical", (8, 6), (7, 6)): {0: True},
			("physical", (8, 6), (9, 6)): {0: True},
			("physical", (8, 6), (8, 5)): {0: True},
			("physical", (8, 6), (8, 7)): {0: True},
			("physical", (8, 7), (7, 7)): {0: True},
			("physical", (8, 7), (9, 7)): {0: True},
			("physical", (8, 7), (8, 6)): {0: True},
			("physical", (8, 7), (8, 8)): {0: True},
			("physical", (8, 8), (7, 8)): {0: True},
			("physical", (8, 8), (9, 8)): {0: True},
			("physical", (8, 8), (8, 7)): {0: True},
			("physical", (8, 8), (8, 9)): {0: True},
			("physical", (8, 9), (7, 9)): {0: True},
			("physical", (8, 9), (9, 9)): {0: True},
			("physical", (8, 9), (8, 8)): {0: True},
			("physical", (9, 0), (8, 0)): {0: True},
			("physical", (9, 0), (9, 1)): {0: True},
			("physical", (9, 1), (8, 1)): {0: True},
			("physical", (9, 1), (9, 0)): {0: True},
			("physical", (9, 1), (9, 2)): {0: True},
			("physical", (9, 2), (8, 2)): {0: True},
			("physical", (9, 2), (9, 1)): {0: True},
			("physical", (9, 2), (9, 3)): {0: True},
			("physical", (9, 3), (8, 3)): {0: True},
			("physical", (9, 3), (9, 2)): {0: True},
			("physical", (9, 3), (9, 4)): {0: True},
			("physical", (9, 4), (8, 4)): {0: True},
			("physical", (9, 4), (9, 3)): {0: True},
			("physical", (9, 4), (9, 5)): {0: True},
			("physical", (9, 5), (8, 5)): {0: True},
			("physical", (9, 5), (9, 4)): {0: True},
			("physical", (9, 5), (9, 6)): {0: True},
			("physical", (9, 6), (8, 6)): {0: True},
			("physical", (9, 6), (9, 5)): {0: True},
			("physical", (9, 6), (9, 7)): {0: True},
			("physical", (9, 7), (8, 7)): {0: True},
			("physical", (9, 7), (9, 6)): {0: True},
			("physical", (9, 7), (9, 8)): {0: True},
			("physical", (9, 8), (8, 8)): {0: True},
			("physical", (9, 8), (9, 7)): {0: True},
			("physical", (9, 8), (9, 9)): {0: True},
			("physical", (9, 9), (8, 9)): {0: True},
			("physical", (9, 9), (9, 8)): {0: True},
		},
		"edge_val": {
			("physical", (0, 0), (1, 0), 0): {},
			("physical", (0, 0), (0, 1), 0): {},
			("physical", (0, 1), (1, 1), 0): {},
			("physical", (0, 1), (0, 0), 0): {},
			("physical", (0, 1), (0, 2), 0): {},
			("physical", (0, 2), (1, 2), 0): {},
			("physical", (0, 2), (0, 1), 0): {},
			("physical", (0, 2), (0, 3), 0): {},
			("physical", (0, 3), (1, 3), 0): {},
			("physical", (0, 3), (0, 2), 0): {},
			("physical", (0, 3), (0, 4), 0): {},
			("physical", (0, 4), (1, 4), 0): {},
			("physical", (0, 4), (0, 3), 0): {},
			("physical", (0, 4), (0, 5), 0): {},
			("physical", (0, 5), (1, 5), 0): {},
			("physical", (0, 5), (0, 4), 0): {},
			("physical", (0, 5), (0, 6), 0): {},
			("physical", (0, 6), (1, 6), 0): {},
			("physical", (0, 6), (0, 5), 0): {},
			("physical", (0, 6), (0, 7), 0): {},
			("physical", (0, 7), (1, 7), 0): {},
			("physical", (0, 7), (0, 6), 0): {},
			("physical", (0, 7), (0, 8), 0): {},
			("physical", (0, 8), (1, 8), 0): {},
			("physical", (0, 8), (0, 7), 0): {},
			("physical", (0, 8), (0, 9), 0): {},
			("physical", (0, 9), (1, 9), 0): {},
			("physical", (0, 9), (0, 8), 0): {},
			("physical", (1, 0), (0, 0), 0): {},
			("physical", (1, 0), (2, 0), 0): {},
			("physical", (1, 0), (1, 1), 0): {},
			("physical", (1, 1), (0, 1), 0): {},
			("physical", (1, 1), (2, 1), 0): {},
			("physical", (1, 1), (1, 0), 0): {},
			("physical", (1, 1), (1, 2), 0): {},
			("physical", (1, 2), (0, 2), 0): {},
			("physical", (1, 2), (2, 2), 0): {},
			("physical", (1, 2), (1, 1), 0): {},
			("physical", (1, 2), (1, 3), 0): {},
			("physical", (1, 3), (0, 3), 0): {},
			("physical", (1, 3), (2, 3), 0): {},
			("physical", (1, 3), (1, 2), 0): {},
			("physical", (1, 3), (1, 4), 0): {},
			("physical", (1, 4), (0, 4), 0): {},
			("physical", (1, 4), (2, 4), 0): {},
			("physical", (1, 4), (1, 3), 0): {},
			("physical", (1, 4), (1, 5), 0): {},
			("physical", (1, 5), (0, 5), 0): {},
			("physical", (1, 5), (2, 5), 0): {},
			("physical", (1, 5), (1, 4), 0): {},
			("physical", (1, 5), (1, 6), 0): {},
			("physical", (1, 6), (0, 6), 0): {},
			("physical", (1, 6), (2, 6), 0): {},
			("physical", (1, 6), (1, 5), 0): {},
			("physical", (1, 6), (1, 7), 0): {},
			("physical", (1, 7), (0, 7), 0): {},
			("physical", (1, 7), (2, 7), 0): {},
			("physical", (1, 7), (1, 6), 0): {},
			("physical", (1, 7), (1, 8), 0): {},
			("physical", (1, 8), (0, 8), 0): {},
			("physical", (1, 8), (2, 8), 0): {},
			("physical", (1, 8), (1, 7), 0): {},
			("physical", (1, 8), (1, 9), 0): {},
			("physical", (1, 9), (0, 9), 0): {},
			("physical", (1, 9), (2, 9), 0): {},
			("physical", (1, 9), (1, 8), 0): {},
			("physical", (2, 0), (1, 0), 0): {},
			("physical", (2, 0), (3, 0), 0): {},
			("physical", (2, 0), (2, 1), 0): {},
			("physical", (2, 1), (1, 1), 0): {},
			("physical", (2, 1), (3, 1), 0): {},
			("physical", (2, 1), (2, 0), 0): {},
			("physical", (2, 1), (2, 2), 0): {},
			("physical", (2, 2), (1, 2), 0): {},
			("physical", (2, 2), (3, 2), 0): {},
			("physical", (2, 2), (2, 1), 0): {},
			("physical", (2, 2), (2, 3), 0): {},
			("physical", (2, 3), (1, 3), 0): {},
			("physical", (2, 3), (3, 3), 0): {},
			("physical", (2, 3), (2, 2), 0): {},
			("physical", (2, 3), (2, 4), 0): {},
			("physical", (2, 4), (1, 4), 0): {},
			("physical", (2, 4), (3, 4), 0): {},
			("physical", (2, 4), (2, 3), 0): {},
			("physical", (2, 4), (2, 5), 0): {},
			("physical", (2, 5), (1, 5), 0): {},
			("physical", (2, 5), (3, 5), 0): {},
			("physical", (2, 5), (2, 4), 0): {},
			("physical", (2, 5), (2, 6), 0): {},
			("physical", (2, 6), (1, 6), 0): {},
			("physical", (2, 6), (3, 6), 0): {},
			("physical", (2, 6), (2, 5), 0): {},
			("physical", (2, 6), (2, 7), 0): {},
			("physical", (2, 7), (1, 7), 0): {},
			("physical", (2, 7), (3, 7), 0): {},
			("physical", (2, 7), (2, 6), 0): {},
			("physical", (2, 7), (2, 8), 0): {},
			("physical", (2, 8), (1, 8), 0): {},
			("physical", (2, 8), (3, 8), 0): {},
			("physical", (2, 8), (2, 7), 0): {},
			("physical", (2, 8), (2, 9), 0): {},
			("physical", (2, 9), (1, 9), 0): {},
			("physical", (2, 9), (3, 9), 0): {},
			("physical", (2, 9), (2, 8), 0): {},
			("physical", (3, 0), (2, 0), 0): {},
			("physical", (3, 0), (4, 0), 0): {},
			("physical", (3, 0), (3, 1), 0): {},
			("physical", (3, 1), (2, 1), 0): {},
			("physical", (3, 1), (4, 1), 0): {},
			("physical", (3, 1), (3, 0), 0): {},
			("physical", (3, 1), (3, 2), 0): {},
			("physical", (3, 2), (2, 2), 0): {},
			("physical", (3, 2), (4, 2), 0): {},
			("physical", (3, 2), (3, 1), 0): {},
			("physical", (3, 2), (3, 3), 0): {},
			("physical", (3, 3), (2, 3), 0): {},
			("physical", (3, 3), (4, 3), 0): {},
			("physical", (3, 3), (3, 2), 0): {},
			("physical", (3, 3), (3, 4), 0): {},
			("physical", (3, 4), (2, 4), 0): {},
			("physical", (3, 4), (4, 4), 0): {},
			("physical", (3, 4), (3, 3), 0): {},
			("physical", (3, 4), (3, 5), 0): {},
			("physical", (3, 5), (2, 5), 0): {},
			("physical", (3, 5), (4, 5), 0): {},
			("physical", (3, 5), (3, 4), 0): {},
			("physical", (3, 5), (3, 6), 0): {},
			("physical", (3, 6), (2, 6), 0): {},
			("physical", (3, 6), (4, 6), 0): {},
			("physical", (3, 6), (3, 5), 0): {},
			("physical", (3, 6), (3, 7), 0): {},
			("physical", (3, 7), (2, 7), 0): {},
			("physical", (3, 7), (4, 7), 0): {},
			("physical", (3, 7), (3, 6), 0): {},
			("physical", (3, 7), (3, 8), 0): {},
			("physical", (3, 8), (2, 8), 0): {},
			("physical", (3, 8), (4, 8), 0): {},
			("physical", (3, 8), (3, 7), 0): {},
			("physical", (3, 8), (3, 9), 0): {},
			("physical", (3, 9), (2, 9), 0): {},
			("physical", (3, 9), (4, 9), 0): {},
			("physical", (3, 9), (3, 8), 0): {},
			("physical", (4, 0), (3, 0), 0): {},
			("physical", (4, 0), (5, 0), 0): {},
			("physical", (4, 0), (4, 1), 0): {},
			("physical", (4, 1), (3, 1), 0): {},
			("physical", (4, 1), (5, 1), 0): {},
			("physical", (4, 1), (4, 0), 0): {},
			("physical", (4, 1), (4, 2), 0): {},
			("physical", (4, 2), (3, 2), 0): {},
			("physical", (4, 2), (5, 2), 0): {},
			("physical", (4, 2), (4, 1), 0): {},
			("physical", (4, 2), (4, 3), 0): {},
			("physical", (4, 3), (3, 3), 0): {},
			("physical", (4, 3), (5, 3), 0): {},
			("physical", (4, 3), (4, 2), 0): {},
			("physical", (4, 3), (4, 4), 0): {},
			("physical", (4, 4), (3, 4), 0): {},
			("physical", (4, 4), (5, 4), 0): {},
			("physical", (4, 4), (4, 3), 0): {},
			("physical", (4, 4), (4, 5), 0): {},
			("physical", (4, 5), (3, 5), 0): {},
			("physical", (4, 5), (5, 5), 0): {},
			("physical", (4, 5), (4, 4), 0): {},
			("physical", (4, 5), (4, 6), 0): {},
			("physical", (4, 6), (3, 6), 0): {},
			("physical", (4, 6), (5, 6), 0): {},
			("physical", (4, 6), (4, 5), 0): {},
			("physical", (4, 6), (4, 7), 0): {},
			("physical", (4, 7), (3, 7), 0): {},
			("physical", (4, 7), (5, 7), 0): {},
			("physical", (4, 7), (4, 6), 0): {},
			("physical", (4, 7), (4, 8), 0): {},
			("physical", (4, 8), (3, 8), 0): {},
			("physical", (4, 8), (5, 8), 0): {},
			("physical", (4, 8), (4, 7), 0): {},
			("physical", (4, 8), (4, 9), 0): {},
			("physical", (4, 9), (3, 9), 0): {},
			("physical", (4, 9), (5, 9), 0): {},
			("physical", (4, 9), (4, 8), 0): {},
			("physical", (5, 0), (4, 0), 0): {},
			("physical", (5, 0), (6, 0), 0): {},
			("physical", (5, 0), (5, 1), 0): {},
			("physical", (5, 1), (4, 1), 0): {},
			("physical", (5, 1), (6, 1), 0): {},
			("physical", (5, 1), (5, 0), 0): {},
			("physical", (5, 1), (5, 2), 0): {},
			("physical", (5, 2), (4, 2), 0): {},
			("physical", (5, 2), (6, 2), 0): {},
			("physical", (5, 2), (5, 1), 0): {},
			("physical", (5, 2), (5, 3), 0): {},
			("physical", (5, 3), (4, 3), 0): {},
			("physical", (5, 3), (6, 3), 0): {},
			("physical", (5, 3), (5, 2), 0): {},
			("physical", (5, 3), (5, 4), 0): {},
			("physical", (5, 4), (4, 4), 0): {},
			("physical", (5, 4), (6, 4), 0): {},
			("physical", (5, 4), (5, 3), 0): {},
			("physical", (5, 4), (5, 5), 0): {},
			("physical", (5, 5), (4, 5), 0): {},
			("physical", (5, 5), (6, 5), 0): {},
			("physical", (5, 5), (5, 4), 0): {},
			("physical", (5, 5), (5, 6), 0): {},
			("physical", (5, 6), (4, 6), 0): {},
			("physical", (5, 6), (6, 6), 0): {},
			("physical", (5, 6), (5, 5), 0): {},
			("physical", (5, 6), (5, 7), 0): {},
			("physical", (5, 7), (4, 7), 0): {},
			("physical", (5, 7), (6, 7), 0): {},
			("physical", (5, 7), (5, 6), 0): {},
			("physical", (5, 7), (5, 8), 0): {},
			("physical", (5, 8), (4, 8), 0): {},
			("physical", (5, 8), (6, 8), 0): {},
			("physical", (5, 8), (5, 7), 0): {},
			("physical", (5, 8), (5, 9), 0): {},
			("physical", (5, 9), (4, 9), 0): {},
			("physical", (5, 9), (6, 9), 0): {},
			("physical", (5, 9), (5, 8), 0): {},
			("physical", (6, 0), (5, 0), 0): {},
			("physical", (6, 0), (7, 0), 0): {},
			("physical", (6, 0), (6, 1), 0): {},
			("physical", (6, 1), (5, 1), 0): {},
			("physical", (6, 1), (7, 1), 0): {},
			("physical", (6, 1), (6, 0), 0): {},
			("physical", (6, 1), (6, 2), 0): {},
			("physical", (6, 2), (5, 2), 0): {},
			("physical", (6, 2), (7, 2), 0): {},
			("physical", (6, 2), (6, 1), 0): {},
			("physical", (6, 2), (6, 3), 0): {},
			("physical", (6, 3), (5, 3), 0): {},
			("physical", (6, 3), (7, 3), 0): {},
			("physical", (6, 3), (6, 2), 0): {},
			("physical", (6, 3), (6, 4), 0): {},
			("physical", (6, 4), (5, 4), 0): {},
			("physical", (6, 4), (7, 4), 0): {},
			("physical", (6, 4), (6, 3), 0): {},
			("physical", (6, 4), (6, 5), 0): {},
			("physical", (6, 5), (5, 5), 0): {},
			("physical", (6, 5), (7, 5), 0): {},
			("physical", (6, 5), (6, 4), 0): {},
			("physical", (6, 5), (6, 6), 0): {},
			("physical", (6, 6), (5, 6), 0): {},
			("physical", (6, 6), (7, 6), 0): {},
			("physical", (6, 6), (6, 5), 0): {},
			("physical", (6, 6), (6, 7), 0): {},
			("physical", (6, 7), (5, 7), 0): {},
			("physical", (6, 7), (7, 7), 0): {},
			("physical", (6, 7), (6, 6), 0): {},
			("physical", (6, 7), (6, 8), 0): {},
			("physical", (6, 8), (5, 8), 0): {},
			("physical", (6, 8), (7, 8), 0): {},
			("physical", (6, 8), (6, 7), 0): {},
			("physical", (6, 8), (6, 9), 0): {},
			("physical", (6, 9), (5, 9), 0): {},
			("physical", (6, 9), (7, 9), 0): {},
			("physical", (6, 9), (6, 8), 0): {},
			("physical", (7, 0), (6, 0), 0): {},
			("physical", (7, 0), (8, 0), 0): {},
			("physical", (7, 0), (7, 1), 0): {},
			("physical", (7, 1), (6, 1), 0): {},
			("physical", (7, 1), (8, 1), 0): {},
			("physical", (7, 1), (7, 0), 0): {},
			("physical", (7, 1), (7, 2), 0): {},
			("physical", (7, 2), (6, 2), 0): {},
			("physical", (7, 2), (8, 2), 0): {},
			("physical", (7, 2), (7, 1), 0): {},
			("physical", (7, 2), (7, 3), 0): {},
			("physical", (7, 3), (6, 3), 0): {},
			("physical", (7, 3), (8, 3), 0): {},
			("physical", (7, 3), (7, 2), 0): {},
			("physical", (7, 3), (7, 4), 0): {},
			("physical", (7, 4), (6, 4), 0): {},
			("physical", (7, 4), (8, 4), 0): {},
			("physical", (7, 4), (7, 3), 0): {},
			("physical", (7, 4), (7, 5), 0): {},
			("physical", (7, 5), (6, 5), 0): {},
			("physical", (7, 5), (8, 5), 0): {},
			("physical", (7, 5), (7, 4), 0): {},
			("physical", (7, 5), (7, 6), 0): {},
			("physical", (7, 6), (6, 6), 0): {},
			("physical", (7, 6), (8, 6), 0): {},
			("physical", (7, 6), (7, 5), 0): {},
			("physical", (7, 6), (7, 7), 0): {},
			("physical", (7, 7), (6, 7), 0): {},
			("physical", (7, 7), (8, 7), 0): {},
			("physical", (7, 7), (7, 6), 0): {},
			("physical", (7, 7), (7, 8), 0): {},
			("physical", (7, 8), (6, 8), 0): {},
			("physical", (7, 8), (8, 8), 0): {},
			("physical", (7, 8), (7, 7), 0): {},
			("physical", (7, 8), (7, 9), 0): {},
			("physical", (7, 9), (6, 9), 0): {},
			("physical", (7, 9), (8, 9), 0): {},
			("physical", (7, 9), (7, 8), 0): {},
			("physical", (8, 0), (7, 0), 0): {},
			("physical", (8, 0), (9, 0), 0): {},
			("physical", (8, 0), (8, 1), 0): {},
			("physical", (8, 1), (7, 1), 0): {},
			("physical", (8, 1), (9, 1), 0): {},
			("physical", (8, 1), (8, 0), 0): {},
			("physical", (8, 1), (8, 2), 0): {},
			("physical", (8, 2), (7, 2), 0): {},
			("physical", (8, 2), (9, 2), 0): {},
			("physical", (8, 2), (8, 1), 0): {},
			("physical", (8, 2), (8, 3), 0): {},
			("physical", (8, 3), (7, 3), 0): {},
			("physical", (8, 3), (9, 3), 0): {},
			("physical", (8, 3), (8, 2), 0): {},
			("physical", (8, 3), (8, 4), 0): {},
			("physical", (8, 4), (7, 4), 0): {},
			("physical", (8, 4), (9, 4), 0): {},
			("physical", (8, 4), (8, 3), 0): {},
			("physical", (8, 4), (8, 5), 0): {},
			("physical", (8, 5), (7, 5), 0): {},
			("physical", (8, 5), (9, 5), 0): {},
			("physical", (8, 5), (8, 4), 0): {},
			("physical", (8, 5), (8, 6), 0): {},
			("physical", (8, 6), (7, 6), 0): {},
			("physical", (8, 6), (9, 6), 0): {},
			("physical", (8, 6), (8, 5), 0): {},
			("physical", (8, 6), (8, 7), 0): {},
			("physical", (8, 7), (7, 7), 0): {},
			("physical", (8, 7), (9, 7), 0): {},
			("physical", (8, 7), (8, 6), 0): {},
			("physical", (8, 7), (8, 8), 0): {},
			("physical", (8, 8), (7, 8), 0): {},
			("physical", (8, 8), (9, 8), 0): {},
			("physical", (8, 8), (8, 7), 0): {},
			("physical", (8, 8), (8, 9), 0): {},
			("physical", (8, 9), (7, 9), 0): {},
			("physical", (8, 9), (9, 9), 0): {},
			("physical", (8, 9), (8, 8), 0): {},
			("physical", (9, 0), (8, 0), 0): {},
			("physical", (9, 0), (9, 1), 0): {},
			("physical", (9, 1), (8, 1), 0): {},
			("physical", (9, 1), (9, 0), 0): {},
			("physical", (9, 1), (9, 2), 0): {},
			("physical", (9, 2), (8, 2), 0): {},
			("physical", (9, 2), (9, 1), 0): {},
			("physical", (9, 2), (9, 3), 0): {},
			("physical", (9, 3), (8, 3), 0): {},
			("physical", (9, 3), (9, 2), 0): {},
			("physical", (9, 3), (9, 4), 0): {},
			("physical", (9, 4), (8, 4), 0): {},
			("physical", (9, 4), (9, 3), 0): {},
			("physical", (9, 4), (9, 5), 0): {},
			("physical", (9, 5), (8, 5), 0): {},
			("physical", (9, 5), (9, 4), 0): {},
			("physical", (9, 5), (9, 6), 0): {},
			("physical", (9, 6), (8, 6), 0): {},
			("physical", (9, 6), (9, 5), 0): {},
			("physical", (9, 6), (9, 7), 0): {},
			("physical", (9, 7), (8, 7), 0): {},
			("physical", (9, 7), (9, 6), 0): {},
			("physical", (9, 7), (9, 8), 0): {},
			("physical", (9, 8), (8, 8), 0): {},
			("physical", (9, 8), (9, 7), 0): {},
			("physical", (9, 8), (9, 9), 0): {},
			("physical", (9, 9), (8, 9), 0): {},
			("physical", (9, 9), (9, 8), 0): {},
		},
		"triggers": {
			"shrubsprint": ("uncovered", "breakcover"),
			"fight": ("sametile",),
			"kill_kobold": ("kobold_alive",),
			"go2kobold": ("aware",),
			"wander": ("standing_still",),
		},
		"prereqs": {
			"shrubsprint": ("not_traveling",),
			"fight": ("kobold_alive", "aware"),
			"kill_kobold": ("unmerciful",),
			"go2kobold": ("kobold_alive", "kobold_not_here"),
			"wander": (),
		},
		"actions": {
			"shrubsprint": ("shrubsprint",),
			"fight": ("fight",),
			"kill_kobold": ("kill_kobold",),
			"go2kobold": ("go2kobold",),
			"wander": ("wander",),
		},
		"rulebook": {
			("physical", "kobold"): (["shrubsprint"], 0.0),
			("physical", "dwarf"): (
				["fight", "kill_kobold", "go2kobold", "wander"],
				0.0,
			),
		},
	}
