INSERT INTO style
(name, fontface, fontsize, spacing, textcolor,
bg_inactive, bg_active, fg_inactive, fg_active) VALUES
    ('BigDark',
     'DejaVu Sans', 14, 6,
     'solarized-base3',
     'solarized-base03',
     'solarized-base2',
     'solarized-base1',
     'solarized-base01'),
    ('SmallDark',
     'DejaVu Sans', 10, 3, 
     'solarized-base3',
     'solarized-base03',
     'solarized-base2',
     'solarized-base1',
     'solarized-base01'),
    ('BigLight',
     'DejaVu Serif', 14, 6,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1'),
    ('SmallLight',
     'DejaVu Serif', 10, 3,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1'),
    ('default_style',
     'DejaVu Serif', 14, 6,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1');
