-- This file is part of LiSE, a framework for life simulation games.
-- Copyright (c) 2013 Zachary Spector,  zacharyspector@gmail.com
INSERT INTO style
(name, fontface, fontsize, spacing, textcolor,
bg_inactive, bg_active, fg_inactive, fg_active) VALUES
    ('BigDark',
     'Sans', 16, 6,
     'solarized-base3',
     'solarized-base03',
     'solarized-base2',
     'solarized-base1',
     'solarized-base01'),
    ('SmallDark',
     'Sans', 12, 3, 
     'solarized-base3',
     'solarized-base03',
     'solarized-base2',
     'solarized-base1',
     'solarized-base01'),
    ('BigLight',
     'Sans', 16, 6,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1'),
    ('SmallLight',
     'Sans', 12, 3,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1'),
    ('default_style',
     'Sans', 16, 6,
     'solarized-base03',
     'solarized-base3',
     'solarized-base02',
     'solarized-base01',
     'solarized-base1');
