-- This file is part of LiSE, a framework for life simulation games.
-- Copyright (c) 2013 Zachary Spector,  zacharyspector@gmail.com
--INSERT INTO hand (window, effect_deck, left, right, top, bot) VALUES ('Main', 'test_deck', 0.2, 0.8, 0.3, 0.1);
